var quotes = [
  "When the world around me is going crazy, I just have to look at my dog to know that good still exists",
  "Everything I know I learned from dogs",
  "Dogs do speak, but only to those who know how to listen",
  "Dogs’ lives are too short. Their only fault, really",
  "Dogs are not our whole life, but they make our lives whole",
  "The better I get to know men, the more I find myself loving dogs",
  "Dogs never bite me. Just Humans",
  "Scratch a dog and you’ll find a permanent job",
  "Anybody who doesn’t know what soap tastes like never washed a dog",
  "Happiness is a warm puppy",
  "What do dogs do on their day off? Can’t lie around – that’s their job",
  "A dog is the only thing on earth that loves you more than he loves himself",
  "Such short little lives our pets have to spend with us, and they spend most of it waiting for us to come home each day",
  "Did you know that there are over 300 words for love in canine?",
  "If there are no dogs in Heaven, then when I die I want to go where they went",
  "You can usually tell that a man is good if he has a dog who loves him",
  "If you don’t own a dog, at least one, there is not necessarily anything wrong with you, but there may be something wrong with your life",
  "If you pick up a starving dog and make him prosperous he will not bite you. This is the principal difference between a dog and man",
  "When an 85-pound mammal licks your tears away, then tries to sit on your lap, it’s hard to feel sad",
  "If I have any beliefs about immortality, it is that certain dogs I have known will go to heaven, and very, very few persons",
  "The greatest fear dogs know is the fear that you will not come back when you go out the door without them",
  "I think dogs are the most amazing creatures; they give unconditional love. For me, they are the role model for being alive",
];

export default quotes;
