var quotes = [
  "When the world around me is going crazy, I just have to look at my dog to know that good still exists",
  "Everything I know I learned from dogs",
  "Dogs do speak, but only to those who know how to listen",
  "Dogs’ lives are too short. Their only fault, really",
  "Dogs are not our whole life, but they make our lives whole",
  "Some of my best leading men have been dogs and horses",
  "The better I get to know men, the more I find myself loving dogs",
  "Dogs never bite me. Just Humans",
  "Scratch a dog and you’ll find a permanent job",
  "The dog is a gentleman; I hope to go to his heaven not man’s",
  "To his dog, every man is Napoleon; hence the constant popularity of dogs",
  "Anybody who doesn’t know what soap tastes like never washed a dog",
  "Happiness is a warm puppy",
  "A lot of shelter dogs are mutts like me",
  "As wonderful as dogs can be, they are famous for missing the point",
  "What do dogs do on their day off? Can’t lie around – that’s their job",
  "A dog is the only thing on earth that loves you more than he loves himself",
  "Such short little lives our pets have to spend with us, and they spend most of it waiting for us to come home each day",
  "Did you know that there are over 300 words for love in canine?",
  "If there are no dogs in Heaven, then when I die I want to go where they went",
  "There is no faith which has never yet been broken, except that of a truly faithful dog",
  "You can usually tell that a man is good if he has a dog who loves him",
  "I don’t understand people who don’t touch their pets. Their cat or dog is called a pet for a reason",
  "If you want a friend in Washington, get a dog",
  "If you don’t own a dog, at least one, there is not necessarily anything wrong with you, but there may be something wrong with your life",
  "If you pick up a starving dog and make him prosperous he will not bite you. This is the principal difference between a dog and man",
  "If a dog will not come to you after having looked you in the face, you should go home and examine your conscience",
  "When an 85-pound mammal licks your tears away, then tries to sit on your lap, it’s hard to feel sad",
  "Everything I know I learned from dogs",
  "Dogs do speak, but only to those who know how to listen",
  "Dogs’ lives are too short. Their only fault, really",
  "Dogs are not our whole life, but they make our lives whole",
  "Some of my best leading men have been dogs and horses",
  "The better I get to know men, the more I find myself loving dogs",
  "Dogs never bite me. Just Humans",
  "Scratch a dog and you’ll find a permanent job",
  "The dog is a gentleman; I hope to go to his heaven not man’s",
  "To his dog, every man is Napoleon; hence the constant popularity of dogs",
  "Anybody who doesn’t know what soap tastes like never washed a dog",
  "Happiness is a warm puppy",
  "Every dog must have his day",
  "My dog is half pit-bull, half poodle. Not much of a watchdog, but a vicious gossip",
  "A lot of shelter dogs are mutts like me",
  "As wonderful as dogs can be, they are famous for missing the point",
  "What do dogs do on their day off? Can’t lie around – that’s their job",
  "A dog is the only thing on earth that loves you more than he loves himself",
  "Such short little lives our pets have to spend with us, and they spend most of it waiting for us to come home each day",
  "Did you know that there are over 300 words for love in canine?",
  "If there are no dogs in Heaven, then when I die I want to go where they went",
  "There is no faith which has never yet been broken, except that of a truly faithful dog",
  "You can usually tell that a man is good if he has a dog who loves him",
  "I don’t understand people who don’t touch their pets. Their cat or dog is called a pet for a reason",
  "If you want a friend in Washington, get a dog",
  "If you don’t own a dog, at least one, there is not necessarily anything wrong with you, but there may be something wrong with your life",
  "If you pick up a starving dog and make him prosperous he will not bite you. This is the principal difference between a dog and man",
  "If a dog will not come to you after having looked you in the face, you should go home and examine your conscience",
  "When an 85-pound mammal licks your tears away, then tries to sit on your lap, it’s hard to feel sad",
  "Dogs are wise. They crawl away into a quiet corner and lick their wounds and do not rejoin the world until they are whole once more",
  "If I have any beliefs about immortality, it is that certain dogs I have known will go to heaven, and very, very few persons",
  "The greatest fear dogs know is the fear that you will not come back when you go out the door without them",
  "I think dogs are the most amazing creatures; they give unconditional love. For me, they are the role model for being alive",
];

export default quotes;
